print("--------------")
print("|   ________ |")
print("|   |Craps!| |")
print("|   -------- |")
print("|    ----    |")
print("|   | o  |   |")
print("|   |/|)o|   |")
print("|   |/ \ |   |")
print("|    ----    |")
print("--------------")